Examen/Examen.UI.Web/Models/ErrorViewModel.cs
namespace Examen.UI.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examen/Examen.UI.Web/Controllers/ArtisteController.cs
using Examen.ApplicationCore.Domain;
using Examen.ApplicationCore.Interfaces;
using Examen.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Examen.UI.Web.Controllers
{
    public class ArtisteController : Controller
    {
        IServiceArtiste sa;
        public ArtisteController(IServiceArtiste sa)
        {
            this.sa = sa;
        }
        // GET: ArtisteController
        public ActionResult Index()
        {
            return View(sa.GetMany());
           
        }

        // GET: ArtisteController/Details/5
        public ActionResult Details(int id)
        {
            return View(sa.GetById(id));
        }

        // GET: ArtisteController/Create
        public ActionResult Create()
        {
          
            return View();

        }

        // POST: ArtisteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Artiste collection)
        {
            try
            {
                sa.Add(collection);
                sa.Commit();
              ;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ArtisteController/Edit/5
        public ActionResult Edit(int id)
        {
            
            return View(sa.GetById(id));
        }

        // POST: ArtisteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Artiste collection)
        {
            try
            {
                sa.Update(collection);
                sa.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ArtisteController/Delete/5
        public ActionResult Delete(int id)
        {
           
            return View(sa.GetById(id));
        }

        // POST: ArtisteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                sa.Delete(sa.GetById(id));
                sa.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Examen/Examen.UI.Web/Controllers/ChansonController.cs
using Examen.ApplicationCore.Domain;
using Examen.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Examen.UI.Web.Controllers
{
    public class ChansonController : Controller
    {
        IServiceChanson sc;
        IServiceArtiste sa;
        public ChansonController(IServiceChanson sc , IServiceArtiste sa )
        {
            this.sc = sc;
            this.sa = sa;
        }
        // GET: ChansonController1
        public ActionResult Index()
        {
           
            return View(sc.GetMany());
        }




        public ActionResult Sort()
        {
            return View(sc.SortChanson());
        }

        // GET: ChansonController1/Details/5
        public ActionResult Details(int id)
        {
            return View(sc.GetById(id));
        }

        // GET: ChansonController1/Create
        public ActionResult Create()
        {
            ViewBag.Artistes= new SelectList(sa.GetMany(), "ArtisteId", "ArtisteId");
            return View();
        }

        // POST: ChansonController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Chanson collection)
        {
            try
            {

                sc.Add(collection);
                sc.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ChansonController1/Edit/5
        public ActionResult Edit(int id)
        {
            return View(sc.GetById(id));
        }

        // POST: ChansonController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Chanson collection)
        {
            try
            {
                sc.Update(collection);
                sc.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ChansonController1/Delete/5
        public ActionResult Delete(int id)
        {
            return View(sc.GetById(id))  ;  
                }

        // POST: ChansonController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                sc.Delete(sc.GetById(id));
                sc.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Examen/Examen.UI.Web/Controllers/HomeController.cs
using Examen.UI.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Examen.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Examen/Examen.UI.Web/Views/Artiste/Create.cshtml
@model Examen.ApplicationCore.Domain.Artiste

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Artiste</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNaissance" class="control-label"></label>
                <input asp-for="DateNaissance" class="form-control" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationalite" class="control-label"></label>
                <input asp-for="Nationalite" class="form-control" />
                <span asp-validation-for="Nationalite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen/Examen.UI.Web/Views/Artiste/Delete.cshtml
@model Examen.ApplicationCore.Domain.Artiste

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artiste</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArtisteId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArtisteId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nationalite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nationalite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Examen/Examen.UI.Web/Views/Artiste/Details.cshtml
@model Examen.ApplicationCore.Domain.Artiste

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Artiste</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArtisteId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArtisteId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nationalite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nationalite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Examen/Examen.UI.Web/Views/Artiste/Edit.cshtml
@model Examen.ApplicationCore.Domain.Artiste

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Artiste</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ArtisteId" class="control-label"></label>
                <input asp-for="ArtisteId" class="form-control" />
                <span asp-validation-for="ArtisteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNaissance" class="control-label"></label>
                <input asp-for="DateNaissance" class="form-control" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationalite" class="control-label"></label>
                <input asp-for="Nationalite" class="form-control" />
                <span asp-validation-for="Nationalite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen/Examen.UI.Web/Views/Artiste/Index.cshtml
@model IEnumerable<Examen.ApplicationCore.Domain.Artiste>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ArtisteId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateNaissance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nationalite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ArtisteId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateNaissance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nationalite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {  id=item.ArtisteId}) |
                @Html.ActionLink("Edit", "Edit", new {  id=item.ArtisteId }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.ArtisteId  })
            </td>
        </tr>
}
    </tbody>
</table>

Examen/Examen.UI.Web/Views/Chanson/Create.cshtml
@model Examen.ApplicationCore.Domain.Chanson

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Chanson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StyleMusical" class="control-label"></label>
                <select asp-for="StyleMusical" asp-items="Html.GetEnumSelectList<Examen.ApplicationCore.Domain.StyleMusical>() " class="form-control"></select>
                <span asp-validation-for="StyleMusical" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titre" class="control-label"></label>
                <input asp-for="Titre" class="form-control" />
                <span asp-validation-for="Titre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateSortie" class="control-label"></label>
                <input asp-for="DateSortie" class="form-control" />
                <span asp-validation-for="DateSortie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VuesYoutube" class="control-label"></label>
                <input asp-for="VuesYoutube" class="form-control" />
                <span asp-validation-for="VuesYoutube" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duree" class="control-label"></label>
                <input asp-for="Duree" class="form-control" />
                <span asp-validation-for="Duree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtisteFk" class="control-label"></label>
                <select asp-for="ArtisteFk" asp-items="ViewBag.Artistes" class="form-control"></select>
                <span asp-validation-for="ArtisteFk" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen/Examen.UI.Web/Views/Chanson/Delete.cshtml
@model Examen.ApplicationCore.Domain.Chanson

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Chanson</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChansonId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChansonId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StyleMusical)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StyleMusical)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateSortie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateSortie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VuesYoutube)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VuesYoutube)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArtisteFk)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArtisteFk)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Examen/Examen.UI.Web/Views/Chanson/Details.cshtml
@model Examen.ApplicationCore.Domain.Chanson

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Chanson</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChansonId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChansonId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StyleMusical)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StyleMusical)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateSortie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateSortie)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VuesYoutube)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VuesYoutube)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArtisteFk)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArtisteFk)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Examen/Examen.UI.Web/Views/Chanson/Edit.cshtml
@model Examen.ApplicationCore.Domain.Chanson

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Chanson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ChansonId" class="control-label"></label>
                <input asp-for="ChansonId" class="form-control" />
                <span asp-validation-for="ChansonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StyleMusical" class="control-label"></label>
                <select asp-for="StyleMusical" asp-items="Html.GetEnumSelectList<Examen.ApplicationCore.Domain.StyleMusical>() " class="form-control"></select>
                <span asp-validation-for="StyleMusical" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Titre" class="control-label"></label>
                <input asp-for="Titre" class="form-control" />
                <span asp-validation-for="Titre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateSortie" class="control-label"></label>
                <input asp-for="DateSortie" class="form-control" />
                <span asp-validation-for="DateSortie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VuesYoutube" class="control-label"></label>
                <input asp-for="VuesYoutube" class="form-control" />
                <span asp-validation-for="VuesYoutube" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duree" class="control-label"></label>
                <input asp-for="Duree" class="form-control" />
                <span asp-validation-for="Duree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtisteFk" class="control-label"></label>
                <input asp-for="ArtisteFk" class="form-control" />
                <span asp-validation-for="ArtisteFk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen/Examen.UI.Web/Views/Chanson/Index.cshtml
@model IEnumerable<Examen.ApplicationCore.Domain.Chanson>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    <input type="submit" value="Sort" asp-controller="Chanson" asp-action="Sort" />
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ChansonId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StyleMusical)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateSortie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VuesYoutube)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArtisteFk)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ChansonId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StyleMusical)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateSortie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VuesYoutube)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArtisteFk)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.ChansonId  }) |
                @Html.ActionLink("Details", "Details", new {  id=item.ChansonId  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.ChansonId  })
                <a asp-controller="Artiste" asp-action="Details" asp-route-id="@item.ArtisteFk">Artiste</a>
            </td>
        </tr>
}
    </tbody>
</table>

Examen/Examen.UI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>